import fc from 'fast-check'
import { expect, it } from 'vitest'
import { JsonLines } from '@openagent/plugin-kit/main'
import { checkAsync } from './check'

const timeout = process.env.FC_EXPLORE ? 130_000 : 35_000
// Pure in-memory framing over the shared transport framer, so this family keeps
// the pure sample budget.
const samples = { normal: 100, explore: 1000 }

// Raw multi-byte text: JSON escaping would hide the UTF-8 boundaries this family splits on.
const units = fc.oneof(
  fc.integer({ min: 0x20, max: 0x7e }).map(code => String.fromCharCode(code)),
  fc.constantFrom('中', '文', '🙂', `e${String.fromCharCode(0x301)}`, String.fromCharCode(0x2028)),
  fc.integer({ min: 0x4e00, max: 0x9fff }).map(code => String.fromCodePoint(code))
)
// Line content never carries \r itself: the framing oracle only has to know \n and
// \r\n terminators, while generated chunk plans still cut between \r and \n bytes.
// \u2028 is content, not a frame separator, so it must survive every chunking.
const line = fc.array(units, { maxLength: 8 }).map(units => units.join(''))
const entry = fc.record({ text: line, terminator: fc.constantFrom('\n', '\r\n') })
// Chunk sizes in bytes with the remainder as the final chunk, as in the Pi RPC family.
const chunkPlan = fc.array(fc.integer({ min: 1, max: 9 }), { minLength: 1, maxLength: 8 })

/** Reference framing computed from the whole byte stream at once: no incremental
 * decoder state, so it is independent of how the stream was cut into chunks. */
function referenceLines(buffer: Buffer): string[] {
  const parts = buffer.toString('utf8').split(/\r?\n/)
  const tail = parts.pop() ?? ''
  const lines = parts.filter(Boolean)
  const trimmed = tail.trim()
  return trimmed ? [...lines, trimmed] : lines
}

it('claude jsonlines chunk boundary assembly keeps framing identical under any chunking', async () => {
  await checkAsync('claude jsonlines chunk boundary assembly keeps framing identical under any chunking', fc.asyncProperty(
    fc.record({
      entries: fc.array(entry, { maxLength: 6 }),
      terminateLast: fc.boolean(),
      plans: fc.array(chunkPlan, { minLength: 1, maxLength: 3 })
    }),
    async scenario => {
      const stream = scenario.entries
        .map((entry, index) =>
          entry.text + (index < scenario.entries.length - 1 || scenario.terminateLast ? entry.terminator : '')
        )
        .join('')
      const buffer = Buffer.from(stream, 'utf8')
      const expected = referenceLines(buffer)
      const run = (sizes: readonly number[]): string[] => {
        const decoder = new JsonLines()
        const lines: string[] = []
        let offset = 0
        for (const size of sizes) {
          lines.push(...decoder.push(buffer.subarray(offset, offset + size)))
          offset = Math.min(offset + size, buffer.length)
        }
        if (offset < buffer.length) lines.push(...decoder.push(buffer.subarray(offset)))
        lines.push(...decoder.end())
        return lines
      }
      // Whole buffer, every generated byte-chunk plan, then one byte per push: the
      // same frame sequence must come out of all of them, so the output depends
      // only on the byte stream and never on a chunk boundary — including
      // boundaries that fall inside a multi-byte character.
      expect(run([buffer.length || 1])).toEqual(expected)
      for (const plan of scenario.plans) expect(run(plan)).toEqual(expected)
      expect(run(Array.from({ length: Math.max(1, buffer.length) }, () => 1))).toEqual(expected)
    }
  ), 'encode generated lines → whole-buffer push → generated byte-chunk plans → byte-at-a-time push → end()', undefined, samples)
}, timeout)
